[project]
name = "42-call-me-maybe"
version = "0.1.0"
description = "Project call me maybe 42"
readme = "README.md"
requires-python = ">=3.12"


dependencies = [
    "numpy>=1.26.0",
    "pydantic>=2.0.0",
    "torch>=2.0.0",
    "transformers>=4.35.0",
    "huggingface-hub>=0.19.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]